services:
  server:
    image: 'minecraft-gtnh:1.0'
    restart: unless-stopped
    ports:
      - '25565:25565'
    volumes:
      - ./worlds:/opt/server/worlds
      - ./logs:/opt/server/logs
      - ./data:/opt/server/_data
