services:
  server:
    image: 'minecraft-gtnh:1.0'
    restart: unless-stopped
    ports:
      - '25565:25565'
    volumes:
      - ./config/minecraft:/opt/server/_data
      - ./worlds:/opt/server/worlds
      - ./logs:/opt/server/logs
      - ./config/modconfigs:/opt/server/config
      - ./config/serverutilities:/opt/server/serverutilities
      - ./backups:/opt/server/backups